apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-api
  namespace: fase4
  labels:
    app: create-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-api
  template:
    metadata:
      labels:
        app: create-api
    spec:
      containers:
        - name: create-api
          image: wesley2019/create-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
