apiVersion: v1
kind: Service
metadata:
  name: create-api-service
  namespace: fase4
spec:
  selector:
    app: create-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
